### ISSUE TITLE
How to run the old tutorials?

### ISSUE THREAD

**Issue by lj-cug** [tribshms/tRIBS#47]
now I cannot use the code to run the old tutorial s downloaded from website? Is there any guides?

**Comment by WrenRaming** [comment]
Hi, we are currently in the process of updating and migrating tRIBS to GitHub. We will have benchmarks scenarios and further instructions for using the model here in the next month or so. Thanks for your interest and patience.

**Comment by WrenRaming** [comment]
Hello @lj-cug, we have updated the tRIBS documentation [here](https://tribshms.readthedocs.io/en/latest/ ). This includes new and updated benchmark examples to work with. I am going to close this issue for now, but let us know if you run into any problems.
